server:
  port: ${IDM_SERVICE_PORT:8081}

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  r2dbc:
    url: r2dbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DATABASE_NAME}
    username: ${POSTGRES_NAME}
    password: ${POSTGRES_PASSWORD}
  liquibase:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DATABASE_NAME}
    user: ${POSTGRES_NAME}
    password: ${POSTGRES_PASSWORD}
    enabled: true
    change-log: classpath:liquibase/db/changelog/db.changelog-master.xml

app:
 util:
   secretKey: ${JWT_SECRET_KEY}
   validityInMin: 60
   validityRefreshInMin: 30
   nameAccessToken: accessToken
   nameRefreshToken: refreshToken
   domainNameFront: ${DOMAIN_NAME_APP_FRONT:http://localhost:8080}
